site_name: Fab Lab Ísafjörður
site_description: >- 
  Make almost anything with us and get expert support to bring creative ideas to life in the Westfjords. visit us to innovate and collaborate!
site_url: https://www.fabisa.is
theme:
  name: material
  custom_dir: overrides
  logo: assets/img/logo/fabisa_logo.png
  favicon: assets/img/favicon.png
#  font:
#    text: Sofadi One # hægt að setja custom font
  features:
    - navigation.tabs
    - navigation.sections
    #- toc.integrate
    - navigation.top 
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: is
  palette:
    - media: "(prefers-color-scheme: light)"  # System preference for light mode
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
      primary: teal
      accent: indigo
    - media: "(prefers-color-scheme: dark)"   # System preference for dark mode
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
      primary: teal
      accent: yellow

plugins:
#  - social  # socail kort sem hægt er að virkja
  - search
  - mkdocs-pdf

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/FabLabIsafjordur
    - icon: fontawesome/brands/github-alt
      link: https://github.com/fablabisastaff/fabisa_site
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/fablabisa/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/fablabisa
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/FabLabIsafjordur
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@FabLabIsa
   # - icon: fontawesome/brands/gitlab
   #   link: https://fablabs.io/labs/fablabisafjordur

      
  extra:
  generator: false
  analytics:
    provider: google
    property: G-XXXXXXXXXX
      
extra_javascript:
  - javascripts/jquery.min.js
  - javascripts/jquery.scrollex.min.js
  - javascripts/jquery.scrolly.min.js
  - javascripts/browser.min.js
  - javascripts/breakpoints.min.js
  - javascripts/main.js
  - javascripts/util.js

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

copyright: |
  &copy; 2024 <a href="https://github.com/fablabisa"  target="_blank" rel="noopener">FabIsa   |  Torfnes 400 Ísafjörður   |   info hjá fabisa.is   |   +354 450 4408  |</a>  

## not working something to look into ##
## added in extra ##
#google_analytics:
#  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
#  - auto  

